# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdown2html.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('contributor', models.CharField(max_length=250)),
                ('publish', models.DateField()),
                ('course_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('content_file', models.FileField(blank=True, upload_to=markdown2html.models.note_slug_directory_path)),
                ('contributor', models.CharField(max_length=250)),
                ('publish', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note_slug', models.SlugField(unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markdown2html.Course')),
            ],
        ),
    ]
