# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlooworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_icon_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='job_website_url',
            field=models.URLField(default=''),
        ),
    ]
